import { NextPage } from "next";
import Head from "next/head";

import AppsView from "@views/apps";

export const Apps: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <AppsView />
    </div>
  );
};

export default Apps;
