import { NextPage } from "next";
import Head from "next/head";

import FindDoctorView from "@views/find-doctor";

export const FindDoctor: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <FindDoctorView />
    </div>
  );
};

export default FindDoctor;
