import { NextPage } from "next";
import Head from "next/head";

import TestimonialsView from "@views/testimonials";

export const Tesnimonials: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <TestimonialsView />
    </div>
  );
};

export default Tesnimonials;
