import { NextPage } from "next";
import Head from "next/head";

import AboutUsView from "@views/about-us";

export const AboutUs: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <AboutUsView />
    </div>
  );
};

export default AboutUs;
